### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by hendrikbengs** [designerei/contao-page-teaser#2]
- [x] Add sorting (alphabetically = page.title, order = page.sorting) via [array_multisort](https://www.php.net/manual/de/function.array-multisort.php)
- [x] Add english translation files under `contao/languages/en/`
- [x] Integrate extension [terminal42/contao-pageimage](https://github.com/terminal42/contao-pageimage)
- [ ] ❓Idea: Explicitly exclude pages
